import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import MswBrowserProvider from "./msw-browser-provider";

if (
  process.env.NEXT_RUNTIME === "nodejs" &&
  process.env.NEXT_PUBLIC_API_MOCKING === "enabled"
) {
  console.log("enabling mocks");
  const { server } = await import("../../mocks/server");
  server.listen();
}

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${geistSans.variable} ${geistMono.variable}`}>
        <MswBrowserProvider>{children}</MswBrowserProvider>
      </body>
    </html>
  );
}
